---
# tasks file for nginx
- name: add nginx
  dnf:
    name: nginx
    state: latest

- name: set firewall to allow service
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
  - http
  - https

- name: start and enable nginx
  service:
    name: nginx
    state: restarted
    enabled: true