# file: 1_provision.yml
---
# https://www.terraform.io/docs/providers/aws/index.html


- name: Provision Openstack Infrastucture using Terraform 
  hosts: localhost
  roles:
  - { role: openstack.infra, tags: ["tf_create"] }

- name: Setup dynamic dns for infra
  hosts: infra
  become: true
  tasks:
  - name: wait for infra to be ready 
    wait_for:
      host: "{{ os_infra_instance_name }}"
      port: 22
      state: started
      timeout: 300

  - include_role:
      name: subscription_manager

  - name: add firewalld
    dnf:
      name: firewalld
      state: latest

  - name: start and enable firewalld
    service:
      name: firewalld
      state: restarted
      enabled: true
  
  - include_role:
      name: dns

  - include_role:
      name: nginx

...
