# file: 1_provision.yml
---
# https://www.terraform.io/docs/providers/aws/index.html


- name: Provision Openstack Infrastucture using Terraform 
  hosts: localhost
  roles:
  - { role: openstack.infra, tags: ["tf_create"] }

- name: Setup dynamic dns for infra
  hosts: infra
  roles:
  - dns
  - nginx

...
