# file: 1_provision.yml
---
# https://www.terraform.io/docs/providers/aws/index.html


- name: Provision Openstack Infrastucture using Terraform 
  hosts: localhost
  roles:
  - { role: openstack.infra, tags: ["tf_create"] }

  post_tasks:
  - name: wait for nodes to be ready 
    - pause:
      minutes: 5
    wait_for:
      host: "{{ item }}"
      port: 22
      state: started
      delay: 30
      timeout: 300
    with_items: "{{ groups.nodes }}"

- name: Setup software on workstation nodes
  hosts: nodes
  become: true
  gather_facts: true
  tasks:
#############################################################
# this is required based on ORock settings 
#############################################################
  - name: Remove clout-init config from Networkmanager
    file:
      path: /etc/NetworkManager/conf.d/99-cloud-init.conf
      state: absent
  - name: restart NetworkManager for subnet DNS
    systemd:
      name: NetworkManager
      state: restarted
      daemon_reload: true
#############################################################
  - include_role:
      name: subscription_manager

  - name: add firewalld
    dnf:
      name: firewalld
      state: latest

  - name: start and enable firewalld
    service:
      name: firewalld
      state: restarted
      enabled: true

  - name: Install podman
    yum:
      name: podman
      state: latest

  - include_role:
      name: atomic_scanner_plugins

  - include_role:
      name: container_check_stp

  - include_role:
      name: jq

  - include_role:
      name: skopeo

  - include_role:
      name: nodejs

  - include_role:
      name: system-user

  - include_role:
      name: cockpit

  - include_role:
      name: upgrade

  - include_role:
      name: subscription_manager
      
...
