# file: 1_provision.yml
---
# https://www.terraform.io/docs/providers/aws/index.html


- name: Provision Openstack Infrastucture using Terraform 
  hosts: localhost
  roles:
  - { role: openstack.infra, tags: ["tf_create"] }

  post_tasks:
  - name: wait for infra to be ready 
    wait_for:
      host: "{{ item }}"
      port: 22
      state: started
      delay: 30
      timeout: 300
    with_items: "{{ groups.infra }}"

- name: Setup nginx and dynamic dns for infra
  hosts: infra
  become: true
  gather_facts: true
  tasks:
#############################################################
# this is required based on ORock settings 
#############################################################
  - name: Remove clout-init config from Networkmanager
    file:
      path: /etc/NetworkManager/conf.d/99-cloud-init.conf
      state: absent
  - name: restart NetworkManager for subnet DNS
    systemd:
      name: NetworkManager
      state: restarted
      daemon_reload: true
#############################################################
  - include_role:
      name: subscription_manager

  - name: add firewalld
    dnf:
      name: firewalld
      state: latest

  - name: start and enable firewalld
    service:
      name: firewalld
      state: restarted
      enabled: true

#############################################################
# move cockpit from port 9090 to 9091
#############################################################
  - name: create the cockpit socket directory
    file:
      path: /etc/systemd/system/cockpit.socket.d
      state: directory
  - name: Copy using inline content
    copy:
      dest: /etc/systemd/system/cockpit.socket.d/listen.conf
      content: |
        [Socket]
        ListenStream=9091
  - name: Allow Apache to listen on tcp port 8888
    seport:
      ports: 9091
      proto: tcp
      setype: websm_port_t
      state: present
  - firewalld:
      port: 9091/tcp
      permanent: yes
      state: enabled
  - name: restart cockpit service
    systemd:
      name: "{{ item }}"
      state: restarted
      daemon_reload: true
    loop:
    - cockpit.service
    - cockpit.socket
#############################################################
  
  - include_role:
      name: dns

  - include_role:
      name: nginx

...
