# file: 1_provision.yml
---
# https://www.terraform.io/docs/providers/aws/index.html


- name: Provision Openstack Infrastucture using Terraform 
  hosts: localhost
  roles:
  - { role: openstack.infra, tags: ["tf_create"] }

- name: Setup dynamic dns for infra
  hosts: infra
  become: true
  gather_facts: false
  tasks:
  - name: wait for infra to be ready 
    wait_for:
      host: "{{ os_infra_instance_name }}"
      port: 22
      state: started
      timeout: 300

  - name: Gather facts for first time
    setup:
#############################################################
# this is required based on ORock settings 
#############################################################
  - name: Remove clout-init config from Networkmanager
    file:
      path: /etc/NetworkManager/conf.d/99-cloud-init.conf
      state: absent
  - name: restart NetworkManager for subnet DNS
    systemd:
      name: NetworkManager
      state: restarted
      daemon_reload: true
#############################################################
  - include_role:
      name: subscription_manager

  - name: add firewalld
    dnf:
      name: firewalld
      state: latest

  - name: start and enable firewalld
    service:
      name: firewalld
      state: restarted
      enabled: true
  
  - include_role:
      name: dns

  - include_role:
      name: nginx

...
