# file: 3_unregister.yml
---

- name: Unregister Nodes 
  become: yes
  hosts: infra
  remote_user: "{{ system_user }}"
    tasks:
    - name: Unsubscribe RHN
      redhat_subscription:
          state: absent

- name: Remove infrastructure using Terraform
  hosts: local_target
  tasks:
  - name: terraform template to remove infrastructure
    terraform:
      project_path: "{{ terraform_working_dir }}"
      state: absent
    register: terraform_template_output

  - debug:
      msg: "{{ terraform_template_output }}"

  - name: clean up terraform artifact directory
    file:
      path: "{{ terraform_working_dir }}/"
      state: absent
