# file: 1_provision.yml
---
# https://www.terraform.io/docs/providers/aws/index.html


- name: Provision Openstack Infrastucture using Terraform 
  hosts: localhost
  roles:
  - { role: openstack.infra, tags: ["tf_create"] }

  post_tasks:
  - name: wait for towers and nodes to be ready 
    wait_for:
      host: "{{ item }}"
      port: 22
      state: started
      delay: 5
      timeout: 300
    with_items: 
    - "{{ groups.nodes }}"
    - "{{ groups.towers }}"


- name: Configure repositories on all RHEL nodes
  become: yes
  remote_user: "{{ workshop_user }}"
  hosts:
    - towers
    - nodes
  gather_facts: yes
  roles:
    - role: subscription_manager

- name: Configure epel on tower nodes
  become: yes
  remote_user: "{{ workshop_user }}"
  hosts: towers
  tasks:
    - name: RHEL 8 on AWS via Cloud Access has no available repositories
      fail:
        msg: "Please use RHSM via user ID/password or org ID/activation key."
      when: cloud_access and ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8'
  roles:
    - role: epel

- name: Remove Red Hat EAP packages
  become: yes
  remote_user: "{{ workshop_user }}"
  hosts:
    - towers
    - nodes
  gather_facts: no
  tasks:
    - package:
        name: eap7-*
        state: absent
      when: jboss is defined
      ignore_errors: yes

- name: Configure software on nodes
  become: yes
  remote_user: "{{ workshop_user }}"
  hosts: towers
  gather_facts: no
  roles:
    - role: nodejs
    - role: ansible.tower
    - role: vscode
    - role: graphical
    - role: system-user
    # - role: powerline

- name: Configure cockpit for web console
  become: yes
  remote_user: "{{ workshop_user }}"
  hosts: towers
  gather_facts: no
  roles:
    - role: cockpit

- name: Stage Maven POMs
  become: yes
  remote_user: "{{ workshop_user }}"
  hosts: nodes
  gather_facts: yes
  roles:
    - role: poms
      when: jboss is defined

- name: Upgrade packages
  become: yes
  remote_user: "{{ workshop_user }}"
  hosts:
    - towers
    - nodes
  roles:
    - role: upgrade

- name: Re-enable SCL repo when upgrade disables it
  become: yes
  remote_user: "{{ workshop_user }}"
  hosts:
    - towers
    - nodes
  gather_facts: yes
  roles:
    - role: subscription_manager 
...
