---
# tasks file for dns
- name: install bind-chroot
  dnf:
    name: bind-chroot
    state: latest
- name: copy named files to chroot
  copy:
    src: /var/named/{{ item }}
    dest: /var/named/chroot/var/named/{{ item }}
    remote_src: true
    owner: named
    group: named
  loop:
  - named.ca
  - named.localhost
  - named.loopback
  - named.empty
- name: copy named directories to chroot
  copy:
    src: /var/named/{{ item }}
    dest: /var/named/chroot/var/named
    remote_src: true
    directory_mode: true
    owner: named
    group: named
  loop:
  - data
  - dynamic
# - name: add config file
#   template:
#     src: templates/named-conf-static.j2
#     dest: /var/named/chroot/etc/named.conf
#     owner: root
#     group: named
#     mode: '0640'
#   notify: restart dns
# - name: add forward zone files
#   template:
#     src: templates/named/forward.zone
#     dest: /var/named/chroot/var/named/{{ forward_zone }}.zone
#     owner: named
#     group: named
#     mode: '0644'
#   notify: restart dns
# - name: add reverse zone files
#   template:
#     src: templates/named/in-addr.arpa.zone.static
#     dest: /var/named/chroot/var/named/{{ reverse_zone }}.in-addr.arpa.zone
#     owner: named
#     group: named
#     mode: '0644'
#   notify: restart dns
- name: set firewall to allow service
  firewalld:
    service: dns
    permanent: true
    immediate: true
    state: enabled
- name: enable and start service
  service:
    name: named-chroot
    state: started
    enabled: true